# Nome da Actions:  
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  # Permite executar na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Especifica a versão do Node.js explicitamente
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Repositório que será utilizado para gerar os arquivos.
      - name: Generate Snake files
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: Aninha8925 # Seu usuário
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check git status
        run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
